---
- name: Ensure that users are created
  hosts: web
  become: true
  tasks:

  - name: Ensure that user is exist
    user: name={{ item.key }} groups=users password={{ item.value.passwd | password_hash('sha512') }} update_password=on_create comment="{{ item.key }}@example.com" create_home=True state=present
    with_dict: "{{ web_users }}"

