---
- name: Ensure that vsftp is configured
  hosts: ftp
  become: true
  tasks:

  - name: Ensure that firewalld is enabled and running
    systemd: name=firewalld state=started enabled=yes

  - name: Ensure that ftp port is open
    firewalld: service=ftp state=enabled permanent=yes immediate=yes

  - name: Ensure that all need pakages are installed
    dnf: name={{ item }} state=present
    loop: ['policycoreutils-python-utils', 'vsftpd']

  - name: Ensure that directory for anonymous download created
    file: path={{ ftp.download_dir }} state=directory owner=ftp group=ftp mode=0755

  - name: Ensure that directory for anonymous upload created
    file: path={{ ftp.upload_dir }} state=directory owner=ftp group=ftp mode=0777

  - name: Ensure that vsftpd is configured
    template: src=vsftpd.conf.j2 dest=/etc/vsftpd/vsftpd.conf owner=root group=root mode=0644
    notify: vsftpd restart

  - name: Ensure that vsftpd is runing and enabled
    systemd: name=vsftpd state=started enabled=yes

  - name: Set selinux context for directories
    sefcontext: target={{ item.target }} setype={{ item.setype }} reload=True state=present
    with_items:
      - { target: "{{ ftp.download_dir }}", setype: "public_content_t" }
      - { target: "{{ ftp.upload_dir }}", setype: "public_content_rw_t" }
    notify: set selinux context

  - name: Set selinux boolean ftpd_anon_write flag on
    seboolean: name=ftpd_anon_write state=yes persistent=yes

  handlers:
  - name: vsftpd restart
    systemd: name=vsftpd.service state=restarted

  - name: set selinux context
    shell: restorecon -R -v {{ item }}
    with_items:
      - "{{ ftp.download_dir }}"
      - "{{ ftp.upload_dir }}"
