---
- name: Ensure that apache is install
  dnf: name=httpd state=present
  tags: apache-install

- name: Ensure that apache is runing and enabled
  systemd: name=httpd state=started enabled=yes
  tags: apache-install

- name: Ensure that http port is open
  firewalld: service=http state=enabled permanent=yes immediate=yes
  tags: apache-install

- name: Ensure that index.html is configured
  template: src=index.html.j2 dest=/var/www/html/index.html owner=root group=root mode=0644
  notify: apache reload
  tags: apache-install

- name: Ensure that apache is uninstall
  dnf: name=httpd state=absent
  tags: apache-uninstall

- name: Ensure that index.html is removed
  file: path=/var/www/html/index.html state=absent
  tags: apache-uninstall

- name: Ensure that http port is disabled
  firewalld: service=http state=disabled permanent=yes immediate=yes
  tags: apache-uninstall
